#!/bin/bash

if [ -z $1 ]; then
	echo "missing argument";
	exit;
fi

cp -rf /home/thang/xampp/assets_WP/wordpress/ /home/thang/xampp/$1
ln -s /home/thang/xampp/assets_WP/revslider /home/thang/xampp/$1/wp-content/plugins/
ln -s /home/thang/xampp/assets_WP/js_composer /home/thang/xampp/$1/wp-content/plugins/
ln -s /home/thang/xampp/assets_WP/contact-form-7 /home/thang/xampp/$1/wp-content/plugins/
ln -s /home/thang/xampp/assets_WP/newsletter/ /home/thang/xampp/$1/wp-content/plugins/
ln -s /home/thang/xampp/assets_WP/woocommerce/ /home/thang/xampp/$1/wp-content/plugins/
ln -s /home/thang/xampp/assets_WP/yith-woocommerce-wishlist/ /home/thang/xampp/$1/wp-content/plugins/
ln -s /home/thang/xampp/assets_WP/yith-woocommerce-zoom-magnifier/ /home/thang/xampp/$1/wp-content/plugins/
ln -s /home/thang/xampp/assets_WP/wp-user-avatar/ /home/thang/xampp/$1/wp-content/plugins/
ln -s /home/thang/xampp/assets_WP/regenerate-thumbnails/ /home/thang/xampp/$1/wp-content/plugins/
sudo chmod -R 777 /home/thang/xampp/$1/
sudo ln -s /home/thang/xampp/$1/ /opt/lampp/htdocs/
chown daemon:daemon /opt/lampp/htdocs/$1
mysql -uroot -hlocalhost -e "CREATE DATABASE $1 character set utf8 collate utf8_unicode_ci;"
mysql -uroot -e "show databases;"
google-chrome localhost/$1 & disown

