#!/bin/bash

for (( i=0 ; ; i++ ))
do

echo "Nhap. ten WP muon\' tao. \n";
echo "Type \" :q \" to exit";
read wp
case $wp in 
	'')
		echo 'empty'
	;;
	':q')
		break ;
	;;
	':Q')
		break ;
	;;
	*)
		cp -rf /home/thang/xampp/assets_WP/wordpress/ /home/thang/xampp/$wp
		ln -s /home/thang/xampp/assets_WP/revslider /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/js_composer /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/contact-form-7 /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/contact-form-7-dynamic-text-extension /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/newsletter/ /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/woocommerce/ /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/yith-woocommerce-wishlist/ /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/yith-woocommerce-zoom-magnifier/ /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/wp-user-avatar/ /home/thang/xampp/$wp/wp-content/plugins/
		ln -s /home/thang/xampp/assets_WP/regenerate-thumbnails/ /home/thang/xampp/$wp/wp-content/plugins/
		sudo chmod -R 777 /home/thang/xampp/$wp/
		sudo ln -s /home/thang/xampp/$wp/ /opt/lampp/htdocs/
		sudo chown daemon:daemon /opt/lampp/htdocs/$wp
		mysql -uroot -hlocalhost -e "CREATE DATABASE $wp character set utf8 collate utf8_unicode_ci;"
		mysql -uroot -e "show databases;"
		array=("${array[@]}" $wp)
	;;
esac
done
for i in ${array[@]} 
do
	google-chrome localhost/$i & disown
done
echo ${array[@]}

		